### ISSUE TITLE
No file named 'setup_conda_env.sh'

### ISSUE THREAD

**Issue by Draculair** [StanfordVL/OmniGibson#283]
![image](https://github.com/StanfordVL/OmniGibson/assets/42961410/684f2a43-168f-46d2-b08e-4a76a394e3ef)
I'm following the instuctions in https://behavior.stanford.edu/omnigibson/getting_started/installation.html#setup to install the omnigibson and I found that the `setup_conda_env.sh` is missed, who can help? thanks

**Comment by wensi-ai** [comment]
Hi @Draculair, that documentation is a bit outdated, please use [this updated link](https://stanfordvl.github.io/OmniGibson/getting_started/installation.html#setup) instead.

**Comment by Draculair** [comment]
Thanks

**Comment by Draculair** [comment]
> Hi @Draculair, that documentation is a bit outdated, please use [this updated link](https://stanfordvl.github.io/OmniGibson/getting_started/installation.html#setup) instead.

I've encountered a new problem. When I run `./scripts/setup.sh`, This error occured:
```
(base) draculair@draculair-ubuntu20:~/OmniGibson$ ./scripts/setup.sh 
We found Isaac Sim installed at /home/draculair/.local/share/ov/pkg/isaac_sim-2022.2.0. OmniGibson will use it by default.
If you want to use a different one, please type in the path containing isaac-sim.sh here (press enter to skip) >>> 

Using Isaac Sim at /home/draculair/.local/share/ov/pkg/isaac_sim-2022.2.0

The new conda environment will be named omnigibson by default.
If you want to use a different name, please type in here (press enter to skip) >>> 

Using omnigibson as the conda environment name

./scripts/setup.sh: 行 30: /home/draculair/.local/share/ov/pkg/isaac_sim-2022.2.0/python: No such file or directory.
```
Can you help? Thank you

**Comment by cgokmen** [comment]
Hi, can you checkout the og-develop branch and try again? This bug was fixed a couple weeks ago but we have not had a chance to release it.

Also we released the docs again on the original link you used. Thanks for the heads up.

**Comment by yuanfei-Wang** [comment]
Hello, I followed the [updated instructions](https://stanfordvl.github.io/OmniGibson/getting_started/installation.html), and I have checkout the branch to og-develop. But I still have a problem when downloading OmniGibson dataset. First, the process failed due to 'scipy' module missing. After I pip installed the module, the process again failed and suggested that the 'omni' module is missing.

**Comment by Draculair** [comment]
I don't know why but you have to run it in the terminal but not in vscode.

**Comment by yuanfei-Wang** [comment]
> I don't know why but you have to run it in the terminal but not in vscode.

Actually, I did run the command in the terminal on a Linux machine. Did you succeed by checkout the og-develop branch?

**Comment by Draculair** [comment]
yeah, I've checkout to og-develop.

**Comment by cgokmen** [comment]
You do have Isaac Sim installed and you can launch it from the Omniverse Launcher, correct?

**Comment by yuanfei-Wang** [comment]
> You do have Isaac Sim installed and you can launch it from the Omniverse Launcher, correct?

Yes I have installed Isaac Sim and I can launch it.

**Comment by cgokmen** [comment]
When you call the omnigibson setup script it finds the right version of Isaac Sim? Also when you go into the Python interpreter in the omnigibson env and you do `import omni` what happens?

**Comment by yuanfei-Wang** [comment]
> When you call the omnigibson setup script it finds the right version of Isaac Sim? Also when you go into the Python interpreter in the omnigibson env and you do `import omni` what happens?

It seems that the setup script finds the right version of Isaac Sim.
![Screenshot from 2023-10-09 14-39-06](https://github.com/StanfordVL/OmniGibson/assets/40728481/e2f61b50-ee01-499d-b3f0-23636f2c4edd)
After the omnigibson environment is created, I call the conda activate command and the following error occurs.
![image](https://github.com/StanfordVL/OmniGibson/assets/40728481/d2b9afdf-2ee0-4d21-95c8-8b0fe1bb2567)
If I ignore this error and continue to run the command to download the dataset, the process collapses due to 'scipy' module missing:
![image](https://github.com/StanfordVL/OmniGibson/assets/40728481/2d50a180-effa-4c2c-bbbc-a7c799e512bb)
After I pip install scipy and rerun the download command, it says the omni module is missing:
![image](https://github.com/StanfordVL/OmniGibson/assets/40728481/1b7410ed-b517-441f-9d9b-bfced6b0debc)
If I go into the python interpreter in omnigibson env and import omni, the same error occurs:
![image](https://github.com/StanfordVL/OmniGibson/assets/40728481/a5ac08ae-daad-4513-a67f-91ade489484c)

**Comment by wensi-ai** [comment]
Hi @yuanfei-Wang, are you using bash or zsh? Could you show us your `~/.local/share/ov/pkgs/isaac_sim-2022.2.0/setup_conda_env.sh`?

**Comment by cgokmen** [comment]
Yes this stuff should be executed using bash. You can go into a bash session (bash --login) and do it there.

**Comment by yuanfei-Wang** [comment]
Yes, I was using zsh. After changing into a bash session, the above errors disappeared. Thanks a lot!
